AWSTemplateFormatVersion: 2010-09-09
Description: Lacework AWS CloudTrail and Config Security Audit Integration (Log Account)
Parameters:
  ResourceNamePrefix:
    Description: >-
      Names of resources created by the stack will be prefixed with this value
      to ensure uniqueness.
    Type: String
    Default: customerdemo
    MinLength: '1'
    MaxLength: '45'
    AllowedPattern: '^[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*$'
    ConstraintDescription: >-
      Invalid resource name prefix value.  Must match pattern
      ^[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*$
  ExternalID:
    Default: 4CEBE3BCEB
    Description: >-
      The cross-account access role created by the stack will use this value in
      the ExternalID.
    Type: String
    MinLength: '10'
    MaxLength: '10'
    AllowedPattern: ^[a-zA-Z0-9=,.@:/-]{10}$
    ConstraintDescription: >-
      Invalid ExternalID value.  Must match pattern
      ^[a-zA-Z0-9=,.@:/-]{10}$.  Must be 10 characters long.
  LaceworkAccount:
    Type: String
    Description: "Enter your Lacework account name. Do not include the '.lacework.net' at the end."
    MinLength: '1'
  ExistingTrailBucketName:
    Description: >-
      Provide the name of the S3 bucket for your existing trail setup.  The
      bucket must be owned by the current account.
    Default: ''
    Type: String
    MaxLength: '128'
  KMSKeyIdentifierArn:
    Description: Provide the ARN of the KMS key for decrypting S3 log files if necessary.
    Default: ''
    Type: String
  SqsQueueUrl:
    Type: String
    Description: The SQS Queue URL.
    AllowedPattern: '^(([^:/?#]+):)?(//([^/?#]*))?([^?#]*)(\?([^#]*))?(#(.*))?'
    ConstraintDescription: Contains a URL/URI pattern only, ie. https://sqs.<region>.amazonaws.com/<account>/<name>
    Default: "https://sqs.<region>.amazonaws.com/<account>/<name>"
  SqsQueueArn:
    Type: String
    Description: The SQS Queue Arn.
  LaceworkAWSAccountId:
    Type: String
    Default: "434813966438"
    MinLength: '12'
    MaxLength: '12'
    AllowedPattern: '^\d{12}$'
    Description: "Enter the Lacework AWS Account ID. Change this FOR TESTING ONLY!"
Conditions:
  UseKMSDecrypt: !Not [!Equals [!Ref KMSKeyIdentifierArn, '']]
Resources:
  LaceworkCWSSACrossAccountAccessRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Join
        - ''
        - - !Ref ResourceNamePrefix
          - '-laceworkcwssarole'
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action: 'sts:AssumeRole'
            Effect: Allow
            Principal:
              AWS: !Join
                - ''
                - - 'arn:aws:iam::'
                  - !Ref LaceworkAWSAccountId
                  - ':root'
            Condition:
              StringEquals:
                'sts:ExternalId': !Sub [ 'lweid:aws:v2:${LaceworkAccount}:${AWS::AccountId}:${ExternalID}', { LaceworkAccount: !Ref LaceworkAccount, ExternalID: !Ref ExternalID } ]
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/SecurityAudit'
  LaceworkCWSPolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: LaceworkCWSPolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: ConsumeNotifications
            Action:
              - 'sqs:GetQueueAttributes'
              - 'sqs:GetQueueUrl'
              - 'sqs:DeleteMessage'
              - 'sqs:ReceiveMessage'
            Effect: Allow
            Resource: !Ref SqsQueueArn
          - Sid: ListLogFiles
            Action:
              - 's3:ListBucket'
            Effect: Allow
            Resource: !Join ['',["arn:aws:s3:::", !Ref ExistingTrailBucketName, "/*AWSLogs/*" ]]
            Condition:
              StringLike:
                's3:prefix':
                  - '*AWSLogs/'
          - Sid: ReadLogFiles
            Action:
              - 's3:Get*'
            Effect: Allow
            Resource: !Join ['',["arn:aws:s3:::", !Ref ExistingTrailBucketName, "/*AWSLogs/*" ]]
          - Sid: GetAccountAlias
            Action:
              - 'iam:ListAccountAliases'
            Effect: Allow
            Resource: '*'
          - Sid: Debug
            Action:
              - 'cloudtrail:DescribeTrails'
              - 'cloudtrail:GetTrailTopics'
              - 'cloudtrail:GetTrailStatus'
              - 'cloudtrail:ListPublicKeys'
              - 's3:GetBucketAcl'
              - 's3:GetBucketPolicy'
              - 's3:ListAllMyBuckets'
              - 's3:GetBucketLocation'
              - 's3:GetBucketLogging'
              - 'sns:GetSubscriptionAttributes'
              - 'sns:GetTopicAttributes'
              - 'sns:ListSubscriptions'
              - 'sns:ListSubscriptionsByTopic'
              - 'sns:ListTopics'
            Effect: Allow
            Resource: '*'
      Roles:
        - !Ref LaceworkCWSSACrossAccountAccessRole
  LaceworkCWSDecryptPolicy:
    Type: 'AWS::IAM::Policy'
    Condition: UseKMSDecrypt
    Properties:
      PolicyName: LaceworkCWSDecryptPolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: DecryptLogFiles
            Action:
              - 'kms:Decrypt'
            Effect: Allow
            Resource: !Ref KMSKeyIdentifierArn
      Roles:
        - !Ref LaceworkCWSSACrossAccountAccessRole
Outputs:
  RoleARN:
    Description: >-
      Cross-account access role ARN to share with Lacework for CloudTrail
      integration
    Value: !GetAtt
      - LaceworkCWSSACrossAccountAccessRole
      - Arn
  ExternalID:
    Description: ExternalID to share with Lacework for CloudTrail integration
    Value: !Sub [ 'lweid:aws:v2:${LaceworkAccount}:${AWS::AccountId}:${ExternalID}', { LaceworkAccount: !Ref LaceworkAccount, ExternalID: !Ref ExternalID } ]
  SQSQueueURL:
    Description: SQS queue URL to share with Lacework for CloudTrail Integration
    Value: !Ref SqsQueueUrl
  TemplateVersion:
    Description: Template version
    Value: '1.1'
